CREATE TABLE python_posts_all(
  id INT(11) NOT NULL AUTO_INCREMENT,
  PostTypeId INT(11) NOT NULL,
  AcceptedAnswerId INT(11) NULL DEFAULT NULL,
  CreationDate DATETIME NULL DEFAULT NULL,
  Score INT(5) NOT NULL DEFAULT '0',
  ViewCount INT(8) NOT NULL DEFAULT '0',
  Body LONGTEXT NULL,
  OwnerUserId INT(11) NULL DEFAULT NULL,
  LastEditorUserId INT(11) NULL DEFAULT NULL,
  LastEditorDisplayName VARCHAR(200) NULL DEFAULT NULL,
  LastEditDate DATETIME NULL DEFAULT NULL,
  LastActivityDate DATETIME NULL DEFAULT NULL,
  Title VARCHAR(500) NULL DEFAULT NULL,
  CommentCount INT(4) NOT NULL DEFAULT '0',
  FavoriteCount INT(6) NOT NULL DEFAULT '0',
  CommunityOwnedDate DATETIME NULL DEFAULT NULL,
  Tags VARCHAR(1000) NULL DEFAULT NULL,
  AnswerCount INT(3) NOT NULL DEFAULT '0',
  BodyWithoutCode LONGTEXT NULL,
  NounClauseRemovedBodyWithoutCode LONGTEXT NULL,
  ParentId INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
COLLATE='utf8mb4_general_ci'
ENGINE=Innodb
AUTO_INCREMENT=25829558;